# Dockerfile.nginx
FROM nginx:alpine

# Copy HTML files into nginx default directory
COPY ./html /usr/share/nginx/html

# Copy custom nginx config
COPY ./settings_files/nginx/nginx.conf /etc/nginx/conf.d/default.conf

# Copy proxy files
COPY ./settings_files/nginx/proxy.conf /config/nginx/proxy.conf
# COPY ./settings_files/nginx/resolver.conf /config/nginx/resolver.conf